influxdb:
  image: influxdb:alpine
  container_name: influxdb
  ports:
    - "8086:8086"
  user: "1000"
  volumes:
    - ${WORKDIR}/influx-data:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  user: "1000"
  links:
    - influxdb
  volumes:
    - ${WORKDIR}/grafana-data:/var/lib/grafana
